config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  

  resources :inventories
  resources :warehouses
  resources :products
  resources :categories

  get '/incidents', controller: :incidents, action: :index, as: :incidents
  delete 'incidents', controller: :incidents, action: :clear
  root 'home#index'

end

app/models/incident.rb
class Incident < ActiveRecord::Base

	def self.log(target, messages)
		messages.each do |message|
		Incident.create(target: target, message: message)
		end
	end
	
	def self.clear_log 
    	Incident.delete_all 
   	end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  def index
  	@incidents = Incident.all.order(created_at: :desc) 
  end
  def clear 
     Incident.clear_log 
     redirect_to root_url 
   end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/index.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><#%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:logged_at) %></th> 
      <th><%= model_class.human_attribute_name(:target) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <!-- <th><#%= model_class.human_attribute_name(:created_at) %></th>-->
      <!-- <th><#%=t '.actions', :default => t("helpers.actions") %></th> -->
    </tr>
  </thead>
  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <!-- <td><%= link_to incident.id, incident_path(incident) %></td> -->
        <td><%=l incident.created_at %></td>  
        <td><%= incident.id %></td>
        <td><%= incident.target %></td>
        <td><%= incident.message %></td>
        <!-- <td><%=l incident.created_at %></td> -->
        <!-- <td> -->
          <!-- <#%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_incident_path(incident), :class => 'btn btn-default btn-xs' %> -->
          <!-- <#%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      incident_path(incident),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %> -->
        <!-- </td> -->
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Clear Log', incidents_path, method: :delete, class: 'btn btn-primary' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_incident_path,
            :class => 'btn btn-primary' %>